In [2]:
import numpy as np
n_inputs = 784
n_layers = 100
x = np.random.randn(n_inputs)
for layer in range(n_layers):
    weights = np.random.randn(n_inputs, n_inputs)
    x = weights @ x
print(x.mean(), x.std())

-1.039908003253946e+143 4.55291765231255e+144


In [3]:
x.shape

(784,)

In [5]:
weights.shape

(784, 784)

In [8]:
import numpy as np
n_inputs = 784
n_layers = 100
x = np.random.randn(n_inputs)
for layer in range(n_layers):
    weights = 0.01 * np.random.randn(n_inputs, n_inputs)
    x = weights @ x
print(x.mean(), x.std())

7.24107053211451e-58 4.725202469078937e-56


In [7]:
import numpy as np
n_inputs = 784
n_layers = 100
x = np.random.rand(n_inputs)
for layer in range(n_layers):
    weights = np.random.rand(n_inputs, n_inputs)
    x = weights @ x
print(x.mean(), x.std())

1.0453444183868017e+259 inf


/Users/ecrespo/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py:195: RuntimeWarning: overflow encountered in multiply
  x = um.multiply(x, x, out=x)


In [9]:
import numpy as np
n_inputs = 784
n_layers = 100
x = np.random.rand(n_inputs)
for layer in range(n_layers):
    weights = 0.01 * np.random.rand(n_inputs, n_inputs)
    x = weights @ x
print(x.mean(), x.std())

1.0925595111236532e+59 2.2570328473239662e+57


In [10]:
a = np.random.rand(n_inputs)

In [11]:
a

array([7.05418554e-01, 6.64414168e-01, 3.14505784e-01, 7.01023845e-01,
       4.49114586e-01, 5.55399046e-02, 9.32941725e-01, 3.59131189e-01,
       2.16284053e-01, 1.06109553e-01, 7.83033025e-01, 9.18797086e-01,
       1.22833248e-01, 8.57905533e-01, 3.51964599e-01, 7.76167284e-01,
       6.24067088e-01, 6.12779442e-01, 8.05074984e-02, 7.94232797e-01,
       2.62337810e-01, 8.12342508e-01, 3.18091338e-02, 1.84569073e-02,
       9.76463861e-01, 4.93242449e-01, 5.47592759e-01, 4.43592976e-01,
       4.00722761e-02, 3.76090287e-02, 5.45502835e-01, 2.04781628e-01,
       3.90251659e-01, 6.19790601e-01, 5.72975474e-02, 5.39989558e-01,
       9.23132349e-01, 5.69523927e-01, 3.28429673e-01, 5.94657389e-01,
       7.14057201e-02, 5.79015247e-01, 8.49004316e-01, 9.45647821e-01,
       6.43024685e-01, 3.58117236e-01, 3.79541286e-01, 8.14334708e-01,
       3.40493859e-01, 9.56428289e-01, 5.37702774e-01, 1.79885677e-01,
       4.17780803e-02, 6.79389173e-01, 2.65111680e-01, 9.97979662e-01,
      

In [12]:
b = np.random.randn(n_inputs)

In [13]:
b

array([ 6.00948943e-01,  1.00288689e+00, -8.56257530e-01, -2.51633573e-03,
        1.13810269e+00,  1.70406453e+00,  3.88229617e-01,  7.69849470e-01,
       -1.17410607e+00,  1.23714447e+00, -1.11316715e+00, -5.57528644e-01,
        1.54896347e+00, -8.19401988e-01,  5.20250583e-01,  7.39405991e-01,
        1.03940258e+00,  3.55815510e-01,  1.51144390e+00,  3.76077600e-01,
        3.90748256e-01, -6.86400525e-01, -3.62179030e-01, -1.24688646e+00,
       -4.97626230e-01,  2.37816002e+00,  7.57834758e-01, -2.77457567e-01,
        6.37020491e-01,  8.91512845e-01,  7.46390557e-01, -1.99871677e+00,
       -1.85364133e+00,  1.62853679e+00,  1.47708449e-01,  3.30335304e-01,
       -1.53137219e+00,  1.96944995e+00, -5.40935033e-01,  7.27881619e-01,
        7.07556374e-02,  1.01174751e+00,  1.01955674e-01,  6.23609464e-01,
        1.70491412e+00, -1.55988317e+00,  3.92332455e-01, -1.65511763e+00,
       -8.03931614e-01,  1.79540273e+00, -8.27923196e-01, -2.25193002e+00,
        9.59342768e-01,  

In [24]:
c = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [25]:
d = np.array([[5,6,7],[5,6,7],[5,6,7]])

In [26]:
c * d

array([[ 5, 12, 21],
       [ 5, 12, 21],
       [ 5, 12, 21]])

In [27]:
c @ d

array([[30, 36, 42],
       [30, 36, 42],
       [30, 36, 42]])

In [28]:
import tensorflow as tf

In [29]:
tf.keras.layers.Dense()

TypeError: __init__() missing 1 required positional argument: 'units'