In [1]:
import tensorflow as tf
tf.random.set_seed(0) #pongo una semilla de aleatorio para obtener todos el mismo resultado, es el punto de partida de los pesos

In [2]:
mnist = tf.keras.datasets.mnist

In [3]:
(x_train, y_train),(x_test, y_test) = mnist.load_data()

In [4]:
x_train, x_test = x_train / 255.0, x_test / 255.0

In [5]:
#defino el modelo de red neuronal o arquitectura
model = tf.keras.models.Sequential([ 
    tf.keras.layers.Flatten(input_shape=(28, 28)), #primera capa aplasta las imagenes, las convierte en un vector y le digo el tamaño 28x28 pixeles, es la entrada que son 784 entradas
    tf.keras.layers.Dense(512, activation=tf.nn.relu), #segunda capa densa de 512 neuronas con función de activació relu
    tf.keras.layers.Dropout(0.2), #capa de dropout del 20%, en cada iteración apaga el 20% de las neuronas al azar para que el resto aprendan de forma robusta
    tf.keras.layers.Dense(10, activation=tf.nn.softmax) #capa densa de 10 neurona para las 10 salidas posibles que son los número del 0 al 9
])

In [6]:
x_train.shape

(60000, 28, 28)

In [7]:
#compilo el modelo donde le añado: algoritmo de optimización (descenso de gradiente),función de perdida (entropia cruzada) y métrica para guiar el proceso de optimización (precisión)
model.compile(optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5) #lo ejecuto 5 veces buscando los pesos, accuracy es el % de aciertos pero son los de entrenamiento que no dice nada, lo importante son los de test

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 6s 98us/sample - loss: 0.2222 - accuracy: 0.9337
Epoch 2/5
60000/60000 [==============================] - 5s 88us/sample - loss: 0.0981 - accuracy: 0.9699
Epoch 3/5
60000/60000 [==============================] - 5s 89us/sample - loss: 0.0698 - accuracy: 0.9780
Epoch 4/5
60000/60000 [==============================] - 5s 90us/sample - loss: 0.0541 - accuracy: 0.9824
Epoch 5/5
60000/60000 [==============================] - 6s 97us/sample - loss: 0.0429 - accuracy: 0.9863


In [9]:
model.evaluate(x_test, y_test) #lo testeo

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.07260559109724127, 0.9774]

In [11]:
#el valor de acierto 97,98% 

In [12]:
#extraer el modelo

In [13]:
model

In [14]:
model.save_weights('pesos_modelo.hdf') #format HDF5 para poder usarlo solo los pesos, pero luego para usarlos debo cargar también el modelo 

In [15]:
model.save('modelo')

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: modelo/assets


In [16]:
#predecir

In [21]:
model.predict(x_test[:1])

array([[7.2144268e-09, 1.8074767e-08, 6.0121891e-07, 1.5704260e-06,
        8.8478178e-13, 1.4455490e-09, 9.6127093e-15, 9.9999785e-01,
        6.8142163e-09, 1.6071004e-08]], dtype=float32)

In [22]:
x_test[:1]

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.

In [18]:
%matplotlib widget
import matplotlib.pyplot as plt

In [19]:
plt.imshow(x_test[0])

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [27]:
x_test[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [29]:
x_test[0].shape #la imagen

(28, 28)

In [30]:
x_test[:1].shape #lo que testeo

(1, 28, 28)

In [31]:
x_test.shape

(10000, 28, 28)

In [34]:
x_test[:2].shape

(2, 28, 28)

In [35]:
l = [1,2,3]

In [38]:
l[0] #devuelve un elemento

1

In [39]:
l[:1] #devuelve una lista con el primer elemento

[1]