In [37]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.0.0'

In [12]:
x = [[2.]]
m = tf.matmul(x, x) #multplica matrices
print(f"Hola x*x: {m}") #f evalua la expresion

Hola x*x: [[4.]]


In [13]:
x

[[2.0]]

In [14]:
type(x)

list

In [15]:
x

[[2.0]]

In [16]:
len(x)

1

In [17]:
m

<tf.Tensor: id=5, shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [18]:
type(m)

tensorflow.python.framework.ops.EagerTensor

In [19]:
m.shape

TensorShape([1, 1])

In [22]:
a = f'{2+2}'

In [23]:
type(a)

str

In [24]:
a

'4'

In [26]:
a = tf.constant([[1,2],[3,4]])

In [27]:
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [28]:
b = tf.add(a,1)

In [29]:
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [30]:
c = a + b

In [31]:
print(c)

tf.Tensor(
[[3 5]
 [7 9]], shape=(2, 2), dtype=int32)


In [32]:
d = a * b

In [33]:
print(d)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [34]:
d

<tf.Tensor: id=10, shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]], dtype=int32)>

In [35]:
a @ b #producto matricial

<tf.Tensor: id=11, shape=(2, 2), dtype=int32, numpy=
array([[10, 13],
       [22, 29]], dtype=int32)>

In [38]:
np.dot(a,b) #a funciones de numpy le puedo pasar matrices de tensorflow

array([[10, 13],
       [22, 29]], dtype=int32)

In [39]:
a.numpy() #paso a numpy un tensor

array([[1, 2],
       [3, 4]], dtype=int32)

In [48]:
def fizzbuzz(max_num):
    counter = tf.constant(0)
    max_num = tf.convert_to_tensor(max_num)
    for num in range(1, max_num.numpy()+1):
        num = tf.constant(num)
        if int(num % 3) == 0 and int(num % 5) == 0: 
            print('FizzBuzz')
        elif int(num % 3) == 0:
            print('Fizz')
        elif int(num % 5) == 0:
            print('Buzz')
        else:
            print(num.numpy())
        counter += 1

fizzbuzz(15)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [45]:
tf.config.experimental.list_physical_devices('GPU')

[]

In [49]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU')]